spring:
  application:
    name: board

  datasource:
    url: jdbc:mysql://localhost:3306/restapi
    username: prac_user
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 1001